name: Deploy Node Application 
on: 
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t lepakshia/nodejs_backend  .
      - name: Publish Image to docker hub
        run: docker push lepakshia/nodejs_backend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull lepakshia/nodejs_backend:latest
      - name: Delete old container
        run: sudo docker rm -f nodejs_backend-container  
      - name: Set up environment variables
        run: |
          touch .env
          echo "DB=${{ secrets.DB }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "JWT_TOKEN=${{ secrets.JWT_TOKEN }}" >> .env
          echo "OTP_AUTHID=${{ secrets.OTP_AUTHID }}" >> .env
          echo "OTP_TOKEN=${{ secrets.OTP_TOKEN }}" >> .env
          echo "S3_ACCESSKEY_KEY=${{ secrets.S3_ACCESSKEY_KEY }}" >> .env
          echo "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}" >> .env
          echo "S3_BUCKET_REGION=${{ secrets.S3_BUCKET_REGION }}" >> .env
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env
      - name: Run Docker Container
        run: sudo docker run -d -p 4000:4000 --restart=always --name nodejs_backend-container --env-file .env lepakshia/nodejs_backend
